name: radar_nowcasting_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pysteps
  - pandas
  - jupyter
  - ipykernel
  - pyqt
  - rasterio
  - geopandas
  - gdal
  - tqdm
  - seaborn
  - pytables
  - h5py
  - dask
  - wradlib
  - contextily
  - pip
  - pip:  # Pip dependencies
    - scikit-learn
    - scikit-image